name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Frontend build
  frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Investigate checkout and repository
      run: |
        echo "=== Current working directory ==="
        pwd
        echo "=== Git status ==="
        git status
        echo "=== Git remote ==="
        git remote -v
        echo "=== Git branch ==="
        git branch -a
        echo "=== Git log (last 5 commits) ==="
        git log --oneline -5
        echo "=== Root directory contents ==="
        ls -la
        echo "=== All directories ==="
        find . -type d -maxdepth 2
        echo "=== Web directory contents ==="
        if [ -d "web" ]; then
          ls -la web/
          echo "=== Web directory permissions ==="
          ls -ld web/
        else
          echo "web directory does not exist"
        fi
        echo "=== Web package.json exists? ==="
        if [ -f "web/package.json" ]; then
          echo "web/package.json exists"
          echo "=== Web package.json contents ==="
          cat web/package.json
        else
          echo "web/package.json does not exist"
        fi
        echo "=== Repository structure (all files) ==="
        find . -type f | head -30
        echo "=== Package.json files ==="
        find . -name "package.json" -type f
    
    - name: Try alternative checkout approach
      run: |
        echo "=== Trying to understand the issue ==="
        echo "Current directory: $(pwd)"
        echo "Git working tree: $(git rev-parse --show-toplevel)"
        echo "Git index: $(git rev-parse --git-dir)"
        echo "=== Checking if this is a shallow clone ==="
        if git rev-parse --is-shallow-repository; then
          echo "This is a shallow repository"
        else
          echo "This is a full repository"
        fi
        echo "=== Checking repository size ==="
        du -sh .
        echo "=== Checking web directory size ==="
        if [ -d "web" ]; then
          du -sh web/
        else
          echo "web directory not found"
        fi
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        if [ -d "web" ] && [ -f "web/package.json" ]; then
          cd web
          npm install
          echo "Dependencies installed successfully"
        else
          echo "ERROR: web directory or package.json not found!"
          echo "Current directory: $(pwd)"
          echo "Available directories:"
          ls -la
          exit 1
        fi
    
    - name: Build application
      run: |
        echo "Building application..."
        if [ -d "web" ] && [ -f "web/package.json" ]; then
          cd web
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Running Next.js build directly..."
          npx next build
          echo "Build completed successfully"
        else
          echo "ERROR: Cannot build - web directory or package.json not found!"
          exit 1
        fi
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:8000' }}

  # Backend verification
  backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        echo "Installing Python dependencies..."
        if [ -d "backend" ] && [ -f "backend/requirements.txt" ]; then
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Python dependencies installed successfully"
        else
          echo "ERROR: backend directory or requirements.txt not found!"
          exit 1
        fi
    
    - name: Verify backend setup
      run: |
        echo "Verifying backend setup..."
        if [ -d "backend" ]; then
          cd backend
          python -c "import fastapi; print('FastAPI imported successfully')"
          python -c "import sqlalchemy; print('SQLAlchemy imported successfully')"
          echo "Backend verification completed"
        else
          echo "ERROR: backend directory not found!"
          exit 1
        fi

  # Deploy to Vercel (only on main branch)
  deploy:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: false
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./web
