name: Development Workflow (Simple)

on:
  push:
    branches: [ develop, feature/*, bugfix/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Development tests and preview
  development:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # No caching to avoid cache-related errors
    
    - name: Install dependencies
      working-directory: ./web
      run: npm install
    
    - name: Check available scripts
      working-directory: ./web
      run: npm run
      continue-on-error: true
    
    - name: Run linting
      working-directory: ./web
      run: npm run lint
      continue-on-error: true
    
    - name: Run type checking
      working-directory: ./web
      run: npx tsc --noEmit
      continue-on-error: true
    
    - name: Build application
      working-directory: ./web
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://localhost:8000' }}

  # Create preview deployment
  preview:
    needs: development
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy Preview to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./web
        vercel-args: '--prod'
